Errors similar to this from vim plugin makers all say this is an issue with your python environment. I have the latest 27x and 3xx builds of python and use a precompiled vim from http://tuxproject.de/projects/vim/. I've uninstalled/reinstalled one or the other version, installed both versions, both with and without paths set. Nothing seems to have an effect.
it ended up in the third option. For some reason, it did not pick up the correct item from rtp. What you could do to fix the problem without digging into the plugin source code and debugging it is set g:UltiSnipsSnippetsDir explicitly to the location where the snippets are stored, i.e. "C:\Users\2c.2c2c.vim\bundle\ultisnips\UltiSnips". Just drop the line
The error originates from the function files_to_edit() in file "C:\Users\2c.2c2c.vim\bundle\ultisnips\plugin\UltiSnips__init__.py". Given a filetype (e.g, "markdown") this function tries figure out where the file with corresponding snippets ("markdown.snippets") might be located in your system. The function checks several places:
I'm also kind of confused why it's checking that directory... Vundle adds rtps to ~/.vim/bundle/addon for anything it installs.
returns python/dyn for both versions, although I've messed with changing paths/uninstalling-reinstalling to have them alone and not alone etc. To see if anything changes. Also, basic python appears to actually work, I can do
Anyways, I haven't seen anyone with an issue like this on Windows, so none of the information is very helpful. Any help is appreciated.